function fb_compute_features(DIR)
%fb_compute_features computes spectral features for a directory of "split"
%files generated by fb_data_split, results are stored in 'syllable_data'
%
%	fb_compute_features(DIR)
%
%	DIR
%	directory to process (string, default: pwd)
%
%this script uses parfor and will automatically use any matlabpool workers
%currently open.

% pre-flight

if nargin<1 | isempty(DIR), DIR=pwd; end

% collect all mat files in the current directory, excluding score files

[status,result]=unix(['find ' DIR ' -type f -name "*.mat" | egrep -v "score"']);
matfile=regexp(result,'\n','split');

lowfs=[];
highfs=[];

parsave=@(filename,features,lowfs,highfs) save(filename,'features','lowfs','highfs');

parfor i=1:length(matfile)-1

	disp([matfile{i}]);

	[path,file,ext]=fileparts(matfile{i});
	
	datdir=fullfile(path,'syllable_data');
	scorefile=fullfile(datdir,[ file '_score.mat']);

	if exist(scorefile,'f')
		warning('File %s already processed, skipping.',matfile{i});
		continue;
	end

	dat=load(matfile{i},'mic_data','fs');

	if ~exist(datdir,'dir')
		mkdir(datdir);
	end

	% compute spectral features

	features=fb_smscore(dat.mic_data,dat.fs);

	% save to score directory 

	parsave(scorefile,features,lowfs,highfs);

end

